import Navbar from "./_components/Navbar"
import "../globals.css"
import { ContextProvider } from "@/context/context"
export const metadata = {
  title: 'AI Freelance',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>


        <Navbar />
   
        {children}</body>
    </html>
  )
}
